name: vuitv
description: A flutter project code base created by VuiTv ................
version: 0.0.5

homepage: https://github.com/vuitv/flutter
repository: https://github.com/vuitv/flutter.git
issue_tracker: https://github.com/vuitv/flutter/issues
documentation: https://github.com/vuitv/flutter

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  intl: ^0.17.0


dev_dependencies:
  build_runner: ^2.3.0

  flutter_test:
    sdk: flutter

  freezed: ^2.2.0
  json_serializable: ^6.5.1
  very_good_analysis: ^3.1.0


