name: vuitv
description: A flutter project code base created by VuiTv ................
version: 3.28.0

homepage: https://github.com/vuitv/flutter
repository: https://github.com/vuitv/flutter.git
issue_tracker: https://github.com/vuitv/flutter/issues
documentation: https://github.com/vuitv/flutter

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  currency_text_input_formatter: ^2.3.0
  flutter:
    sdk: flutter

  flutter_multi_formatter: ^2.13.7
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0


