name: vuitv
description: A Utils Dart package.
version: 0.0.1+1

homepage: https://vuitv.dev
repository:
issue_tracker:
documentation:

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.20.2
  very_good_analysis: ^2.4.0
