name: vuitv
description: A flutter project code base created by VuiTv ................
version: 3.27.1

homepage: https://github.com/vuitv/flutter
repository: https://github.com/vuitv/flutter.git
issue_tracker: https://github.com/vuitv/flutter/issues
documentation: https://github.com/vuitv/flutter

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  currency_text_input_formatter: ^2.2.9
  flutter:
    sdk: flutter

  flutter_multi_formatter: ^2.13.7
  freezed_annotation: ^3.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^7.0.0


