name: vuitv
description: A flutter project code base created by VuiTv ................
version: 0.3.0

homepage: https://github.com/vuitv/flutter
repository: https://github.com/vuitv/flutter.git
issue_tracker: https://github.com/vuitv/flutter/issues
documentation: https://github.com/vuitv/flutter

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  currency_text_input_formatter: ^2.1.9
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.4

  flutter_test:
    sdk: flutter

  freezed: ^2.3.4
  json_serializable: ^6.6.2
  very_good_analysis: ^4.0.0+1


